# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20170710_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
