# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time'], 'permissions': (('plus_comment', 'Add Comment'), ('del_comment', 'Delete Comment'))},
        ),
    ]
