# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20170716_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time'], 'permissions': (('see_comment', 'Can only see comments'),)},
        ),
    ]
